// src/modules/auth/pages/SignInPage.tsx
import {
  Button,
  Card,
  Checkbox,
  Form,
  FormProps,
  Input,
  Typography,
} from "antd";
import { useEffect } from "react";
import { signIn } from "../../../services/AuthService";
import useToastStore from "../../../store/ToastStore";
import { useNavigate } from "react-router-dom";

type FieldType = {
  username?: string;
  password?: string;
  remember_me?: string;
};

export default function SignInPage({
  pageInformation,
}: {
  pageInformation: any;
}) {
  const { setToast } = useToastStore();
  const navigate = useNavigate();
  const [form] = Form.useForm<FieldType>();
  const onFinish: FormProps<FieldType>["onFinish"] = (values) => {
    signIn(values)
      .then((res) => {
        let data = res.data.data;
        localStorage.setItem("access_token", data.access_token);
        localStorage.setItem("refresh_token", data.refresh_token);
        setToast({
          show: true,
          content: res.data.result.message,
          type: "success",
        });
        navigate("/home");
      })
      .catch((error) => {
        setToast({
          show: true,
          content: error.response.data.result.message,
          type: "error",
        });
      });
  };

  const onFinishFailed: FormProps<FieldType>["onFinishFailed"] = (
    errorInfo
  ) => {};

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Enter") {
        event.preventDefault();
        form.submit();
      }
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [form]);

  return (
    <div>
      <div
        style={{
          width: "100%",
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          backgroundImage: `url(${pageInformation["sign_in_background"]})`,
          backgroundSize: "cover",
        }}
      >
        <Card style={{ width: "30%", zIndex: 100 }}>
          <Form
            form={form}
            name="basic"
            labelCol={{ span: 8 }}
            wrapperCol={{ span: 16 }}
            style={{ maxWidth: 600 }}
            initialValues={{ remember_me: true }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <Typography.Title level={2} style={{ textAlign: "center" }}>
              {pageInformation["sign_in_title"]}
            </Typography.Title>
            <Form.Item<FieldType>
              label={pageInformation["sign_in_username"]}
              name="username"
              rules={[
                { required: true, message: "Please input your username!" },
              ]}
            >
              <Input />
            </Form.Item>

            <Form.Item<FieldType>
              label={pageInformation["sign_in_password"]}
              name="password"
              rules={[
                { required: true, message: "Please input your password!" },
              ]}
            >
              <Input.Password />
            </Form.Item>

            <Form.Item<FieldType>
              name="remember_me"
              valuePropName="checked"
              wrapperCol={{ offset: 8, span: 16 }}
            >
              <Checkbox>Remember me</Checkbox>
            </Form.Item>

            <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
              <Button type="primary" htmlType="submit">
                {pageInformation["sign_in_title"]}
              </Button>
            </Form.Item>
          </Form>
        </Card>
      </div>
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: "100%",
          backgroundColor: "rgba(0, 0, 0, 0.5)", // Màu đen với độ mờ 50%
          zIndex: 1,
        }}
      ></div>
    </div>
  );
}

// src/components/auth/SignInPage.vue
<script setup lang="ts">
import { AuthService } from "@/services/AuthService";
import { useToastStore } from "@/stores/toast";
import { useRouter } from "vue-router";

const router = useRouter();

const username = ref<string>("");
const password = ref<string>("");
const showPassword = ref<boolean>(false);

let usernameRules = [(v: string) => !!v || "Username is required"];

let passwordRules = [(v: string) => !!v || "Password is required"];

const onLoginToSell = () => {
  let request = {
    username: username.value,
    password: password.value,
  };
  AuthService.signIn(request).then((res) => {
    useToastStore().showSuccess("Đăng nhập thành công");
    localStorage.setItem("access_token", res.data.data.access_token);
    router.push("/sell");
  });
};

const onLoginToAdmin = () => {
  let request = {
    username: username.value,
    password: password.value,
  };
  AuthService.signIn(request).then((res) => {
    localStorage.setItem("access_token", res.data.data.access_token);
    router.push("/otp");
  });
};

const handleKeyPress = (e: any) => {
  if (e.key === "Enter" && e.altKey) {
    onLoginToAdmin();
  } else if (e.key === "Enter") {
    onLoginToSell();
  }
};
</script>

<template>
  <div
    :style="{
      width: '100%',
      height: '100vh',
      paddingRight: '25px',
      display: 'flex',
      justifyContent: 'end',
      alignItems: 'center',
      backgroundImage:
        'url(https://res.cloudinary.com/blogweb/image/upload/v1730973208/pos/oiryqbpc5safyepd2cdu.jpg)',
      backgroundSize: 'cover',
      backgroundPosition: 'right'
    }"
  >
    <v-card
      :style="{
        width: '30%',
        zIndex: 100,
        backgroundColor: 'rgba(255, 255, 255, 0.8)'
      }"
    >
      <v-card-title class="text-center">
        <h2>Đăng nhập hệ thống</h2>
      </v-card-title>
      <v-card-text>
        <v-form @submit.prevent @keydown="handleKeyPress" autocomplete="off">
          <v-text-field
            type="text"
            v-model="username"
            :rules="usernameRules"
            label="Username"
            variant="solo-filled"
          ></v-text-field>

          <v-text-field
            :type="showPassword ? 'text' : 'password'"
            v-model="password"
            :rules="passwordRules"
            label="Password"
            variant="solo-filled"
          >
            <template v-slot:append-inner>
              <v-icon
                :color="showPassword ? 'primary' : 'grey'"
                @click="showPassword = !showPassword"
              >{{ showPassword ? "mdi-eye-off" : "mdi-eye" }}
              </v-icon>
            </template>
          </v-text-field>

          <v-btn class="mt-2 w-100" color="secondary" @click="onLoginToSell">
            Đăng nhập vào trang bán hàng
          </v-btn>
          <v-btn class="mt-2 w-100" color="primary" @click="onLoginToAdmin">
            Đăng nhập vào trang quản lý
          </v-btn>
        </v-form>
      </v-card-text>
    </v-card>
  </div>
  <div
    :style="{
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      zIndex: 1
    }"
  ></div>
</template>

<style scoped lang="sass"></style>
